# Generated by Django 3.1.1 on 2020-09-23 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20200923_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='specialty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='jobs.specialty'),
        ),
    ]
