# Generated by Django 3.1.1 on 2020-09-24 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0006_auto_20200923_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('surname', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(choices=[('Не ищу работу', 'Not Looking'), ('Рассматриваю предложения', 'Considering'), ('Ищу работу', 'Looking')], max_length=100, null=True)),
                ('salary', models.PositiveIntegerField(null=True)),
                ('grade', models.CharField(choices=[('Стажер', 'Trainee'), ('Junior', 'Junior'), ('Middle', 'Middle'), ('Senior', 'Senior'), ('Lead', 'Lead')], max_length=100, null=True)),
                ('education', models.TextField(null=True)),
                ('experience', models.TextField(null=True)),
                ('portfolio', models.TextField(null=True)),
                ('specialty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='jobs.specialty')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
